<?php//include 'src/Google_Client.php'; require_once 'src/contrib/Google_PlusService.php';require_once 'src/contrib/Google_Oauth2Service.php';session_start();$client = new Google_Client();$client->setApplicationName("Asig 18 Sign in with GPlus"); $client->setScopes(array('https://www.googleapis.com/auth/userinfo.email', 'https://www.googleapis.com/auth/plus.me')); $client->setClientId('365053567550-9tmla5b3048l2op10rt24i2epm7ru6a6.apps.googleusercontent.com'); $client->setClientSecret('SDuZZc3gRqqBjlArd6ISLyeD'); $client->setRedirectUri('http://localhost/hubspot'); $plus 		= new Google_PlusService($client);$oauth2 	= new Google_Oauth2Service($client); if(isset($_GET['code'])) {	$client->authenticate(); 	$_SESSION['access_token'] = $client->getAccessToken(); 	header('Location: http://' . $_SERVER['HTTP_HOST'] . $_SERVER['PHP_SELF']);}if(isset($_SESSION['access_token'])) {	$client->setAccessToken($_SESSION['access_token']);}if ($client->getAccessToken()) {  $user 		= $oauth2->userinfo->get();  $me 			= $plus->people->get('me');  $optParams 	= array('maxResults' => 100);  $activities 	= $plus->activities->listActivities('me', 'public',$optParams);  $_SESSION['access_token'] 		= $client->getAccessToken();  $email 							= filter_var($user['email'], FILTER_SANITIZE_EMAIL); } else {	$authUrl = $client->createAuthUrl();}if(isset($me)){ 	$_SESSION['gplusuer'] = $me; }if(isset($_GET['logout'])) {  unset($_SESSION['access_token']);  unset($_SESSION['gplusuer']);  session_destroy();  header('Location: http://' . $_SERVER['HTTP_HOST'] . $_SERVER['PHP_SELF']); }?><!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd"> 
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en"> 
<head> <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>WebPlant Admin Login</title> <style>body{	margin: 0;	padding: 0;	font-family: arial;	color: #2C2C2C;	font-size: 14px;}h1 a{	color:#2C2C2C;	text-decoration:none;}h1 a:hover{	text-decoration:underline;}a{	color: #069FDF;}.wrapper{	margin: 0 auto;	width: 1000px;}.mytable{	width: 700px;	margin: 0 auto;	border:2px dashed #17A3F7;	padding: 20px;}</style>
<meta http-equiv=Content-Type content="text/html; charset=windows-1252" /> 
<link  href="css/reset.css" rel="stylesheet" type="text/css" /> 
<link  href="css/login.css" rel="stylesheet" type="text/css" /> 
</head> 
<body id="page-login"> 
<div class="login-container"> 
<h1>WebPlant Admin Panel</h1> 
  <div class="login-box">     	  <?php 							if(isset($_GET['error'])){								if($_GET['error']=='1'){								echo "<p><label class=h_error>Please enter a User ID and pasword</label>";								}																if($_GET['error']=='2'){								echo "<p><label class=h_error>Invalid User ID or password. <br>Please try again</label>";								}									if($_GET['loginerror']=='y'){								echo "<p><label class=h_error>Please login before proceeding.</label>";								}								}								?>    <div class="wrapper"><?php if(isset($authUrl)) {	echo "<a class='login' href='$authUrl'><img src=\"google-login-button-asif18.png\" alt=\"Google login using php api for your website\" title=\"login with google\" style='width:20%;margin-left:-30%;'/></a>";	} else {	echo "<a class='logout' href='index.php?logout' style='width:20%;margin-left:-40%;'>Logout</a>";}if(isset($_SESSION['gplusuer'])){ ?><br/><br/>	<?php $userEmail =$user['email']; $username = "root";$password = "";$hostname = "localhost"; $con = mysql_connect($hostname, $username, $password)   or die("Unable to connect to MySQL");mysql_select_db("thewebpl_hubspot");	$check_exists = "Select * from webadmin where email='$userEmail'";		$check_result = mysql_query($check_exists);		$row = mysql_fetch_array($check_result);		date_default_timezone_set('Asia/Kolkata');		$now=date("Y-m-d H:i:s");		 		if(mysql_num_rows($check_result) > 0) {			$_SESSION['loggedIn'] = "Y";			$_SESSION['type']=$row['type'];			$_SESSION['name']=$row['name'];			$_SESSION['userRole'] = $row['userRole'];			header("location:welcome.php");				}		else{		echo "<span style='width:20%;margin-left:-40%;'>Sorry You are not an authorised user<span>";		} } ?></div>  
  </div> 
</div>
</body>
<script>
document.getElementsByName('employee_id1')[0].focus();
</script>
</html>